### ISSUE TITLE
Publish manylinux1 binary wheels to PyPi?

### ISSUE THREAD

**Issue by messense** [PetterS/quickjs#1]

**Comment by PetterS** [comment]
Yes that would be really nice but I don't know how to do it. Help is welcome.

When I build with bdist_wheel, pypi rejects the wheel because it's not manylinux.

**Comment by PetterS** [comment]
Even more important are Windows wheels I guess? Since installing from source on Linux is pretty simple.

**Comment by PetterS** [comment]
Looks like Docker is required and I can't do it locally on my machine.

**Comment by PetterS** [comment]
Windows wheels are not currently possible either. I have the toolchain installed to compile them, but QuickJS itself is not compatible with Visual Studio 2017 (required for Python 3.7).

```
cutils.h(137): error C2061: syntax error: identifier 'packed_u64'
```
etc. There are many more errors, like ranges in switch statements that are not supported.

**Comment by PetterS** [comment]
Will accept help setting up e.g. a Travis job to build manylinux wheels.
