### ISSUE TITLE
1.19.0 install error

### ISSUE THREAD

**Issue by EkkoG** [PetterS/quickjs#110]
❯ pip3 install quickjs
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting quickjs
  Downloading quickjs-1.19.0.tar.gz (456 kB)
     |████████████████████████████████| 456 kB 502 kB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/08/66vfs65n1zqbz39vhgtn8k440000gn/T/pip-install-60pagqv8/quickjs_c64f5c770a864122a4e112529073203b/setup.py'"'"'; __file__='"'"'/private/var/folders/08/66vfs65n1zqbz39vhgtn8k440000gn/T/pip-install-60pagqv8/quickjs_c64f5c770a864122a4e112529073203b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/08/66vfs65n1zqbz39vhgtn8k440000gn/T/pip-pip-egg-info-mndrmekk
       cwd: /private/var/folders/08/66vfs65n1zqbz39vhgtn8k440000gn/T/pip-install-60pagqv8/quickjs_c64f5c770a864122a4e112529073203b/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/08/66vfs65n1zqbz39vhgtn8k440000gn/T/pip-install-60pagqv8/quickjs_c64f5c770a864122a4e112529073203b/setup.py", line 7, in <module>
      CONFIG_VERSION = open("upstream-quickjs/VERSION").read().strip()
  FileNotFoundError: [Errno 2] No such file or directory: 'upstream-quickjs/VERSION'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/13/73/15071652d8c830290a6d56e7f3d8eee7e8ddd0b92dfe2ff5c5c29ffaf6b9/quickjs-1.19.0.tar.gz#sha256=1cce45b12ecf9e308fb57ae07305837faf1f8c861cfb92528cd82497b1a5404f (from https://pypi.org/simple/quickjs/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading quickjs-1.18.0.tar.gz (455 kB)
     |████████████████████████████████| 455 kB 4.8 MB/s            
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: quickjs
  Building wheel for quickjs (setup.py) ... done
  Created wheel for quickjs: filename=quickjs-1.18.0-cp39-cp39-macosx_12_0_x86_64.whl size=528553 sha256=ef99570563c484ec95c0503ed734fe4a08507fb64c214daa9cf32ff2c79f9c6c
  Stored in directory: /Users/ciel/Library/Caches/pip/wheels/52/b8/5e/7a013762910a9efe19887bd5816a3ddfbba7c2b148b7a19acc
Successfully built quickjs
Installing collected packages: quickjs
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed quickjs-1.18.0
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.

**Comment by qwenger** [comment]
Sorry for that, should be fixed now in master. Also, I'm working re-introducing binary distributions from the next release on.

**Comment by qwenger** [comment]
For now, I released version 1.19.1 (source distribution only) with this bug fixed.
