### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by HexPandaa** [PetterS/quickjs#125]
As there is no pre-built wheel for Python 3.11, when installing on Windows the package is built from source and the compilation fails on a recent compiler (`invalid numeric argument '/Werror=incompatible-pointer-types'` on VS2022).

Would you consider pushing wheels for Python 3.11 on pypi in order to ease the installation?

**Comment by UchihaYuki** [comment]
Is there a way to install this package on Linux?
I got the following error:

> ERROR: Could not build wheels for quickjs, which is required to install pyproject.toml-based projects

**Comment by qwenger** [comment]
An official wheel is now provided. Sorry for the delay.
