### ISSUE TITLE
python3.11 support

### ISSUE THREAD

**Issue by F11st** [PetterS/quickjs#127]
I compiled the wheel file of `quickjs` in python3.11😜
installation method `pip install <wheel_file_path>`
[quickjs-1.19.2-cp311-cp311-win_amd64.zip](https://github.com/PetterS/quickjs/files/12180440/quickjs-1.19.2-cp311-cp311-win_amd64.zip)

**Comment by clyonbits** [comment]
i love you

**Comment by xBigPanda** [comment]
I love you

**Comment by SeaL773** [comment]
I love you

**Comment by 0dminnimda** [comment]
Seems nice overall

---

Just in case: be wary with compiled wheels not from official package managers, it is not too differenet from an executable, so do your checks before installing and running this.

**Comment by git3fdsfkjadkfsspa** [comment]
I love you bro

**Comment by F11st** [comment]
> Seems nice overall
> 
> Just in case: be wary with compiled wheels not from official package managers, it is not too differenet from an executable, so do your checks before installing and running this.

I guarantee that there are no harmful payloads in it and that it is fully compiled from official sources XD

**Comment by UchihaYuki** [comment]
Is there one for linux?
https://github.com/ading2210/poe-api/issues/187#issuecomment-1712697435

**Comment by qwenger** [comment]
An official wheel is now provided. Sorry for the delay.
