### ISSUE TITLE
dependency on libgcc_s_seh-1.dll

### ISSUE THREAD

**Issue by SeaHOH** [PetterS/quickjs#25]
Hi~! I am a user of your excellent works.

From v1.8.0, the PyPi wheel releases depend on a bothered **libgcc_s_seh-1.dll**. I heard that, usually the MinGW64 compiled result only depend on win32 API. So, this dependency can be removed?

**Comment by PetterS** [comment]
Hmm... I used the same compiler, library and build script for the versions prior to 1.8.0.

Not sure how this happened. In the meantime, use a version prior to 1.8.0 I suppose.

**Comment by PetterS** [comment]
Just adding `-static -static-libgcc` should probably work. I'll try this,

**Comment by SeaHOH** [comment]
I try compile use MSYS2 MinGW 64-bit (GCC 9.2.0-2), but there are too many errors in comparison of integer. I don‘t understand Clang at all, is the GCC's version number too hight?

![msys2-mingw-gcc9](https://user-images.githubusercontent.com/8470820/73219046-2df2ad00-4196-11ea-8055-f8ac63a443aa.png)

**Comment by PetterS** [comment]
It's using the symbols `__udivti3` and `__umodti3` only.

**Comment by PetterS** [comment]
Thanks for this report! A fix will be merged shortly and I will push a static version to PyPi.

**Comment by PetterS** [comment]
1.10.0 is now available on Pypi with this fix.

**Comment by SeaHOH** [comment]
Good job! :+1:
Would you like to release more wheel versions? `win32`, `cp38`, etc. I think these would be very popular.

**Comment by PetterS** [comment]
I will not release for win32. Maybe Python 3.8, shouldn't be too hard so set up multiple venvs I think. Perhaps next release.
