### ISSUE TITLE
Thoughts on calling Python from QuickJS?

### ISSUE THREAD

**Issue by cabrrtt** [PetterS/quickjs#27]
With module loading having landed, calling quickjs from python is a joy! Fantastic stuff.
A simple, sandboxed Test262 compliant JS engine has long been elusive (not withstanding security vulnerabilities in quickjs itself). What are your thoughts on calling registered python functions from within the JS context?

**Comment by PetterS** [comment]
Yes, that would be good. I don't have a use case for it myself, that's why I haven't implemented it.

So I'll do it on my free time, when I find the time.

**Comment by PetterS** [comment]
One issue to consider here is that we must re-aquire the GIL before calling into Python code again.

**Comment by PetterS** [comment]
API suggestions?

**Comment by cabrrtt** [comment]
How do we feel about the use of setGlobals as implemented in https://github.com/stefano/pyduktape/blob/master/README.rst

**Comment by cabrrtt** [comment]
Alternative approach might be an addCallback, similar time that implemented in the rust bindings by theduke https://github.com/theduke/quickjs-rs/blob/master/README.md
