### ISSUE TITLE
Performance down VS standalone application

### ISSUE THREAD

**Issue by SeaHOH** [PetterS/quickjs#28]
See the test, I don't know how it happened.

CPU:
- AMD A6-3500 APU ( 3 core @ 135MHz * 6 )

System:
- Windows 7 64 bit

GCC:
- GCC 9.2.0 @ MSYS2 MinGw 64 bit

Test code:
```
for ( let i = 1; i < 10 ** 7; i ++ ) { i + 1 }
```
Case A: 
- _quickjs.cp38-win_amd64.pyd
- Average time cost about 4700 ms

Case B: 
- qjs.exe 64 bit
- Average time cost about 800 ms

**Comment by PetterS** [comment]
Can you post the compiler flags used to compile qjs.exe?

**Comment by SeaHOH** [comment]
Sorry, I made a mistake: in case use qjs.exe, my unittest skip run this code.
So, I tested them again. The real situation is contrary!!

Case A: 
- _quickjs.cp38-win_amd64.pyd
- Average time cost about 4700 ms

Case B: 
- qjs.exe 64 bit [Makefile](https://github.com/PetterS/quickjs/files/4142629/Makefile.txt)
- Average time cost about 5000 s
