### ISSUE TITLE
need api to list all global variables

### ISSUE THREAD

**Issue by pianoboysai** [PetterS/quickjs#34]
is it possible to provide one?

**Comment by PetterS** [comment]
Isn't this just `Object.keys(globalThis)`?

**Comment by pianoboysai** [comment]
For example
`
context = quickjs.Context()                                                                                                 
code = "random_name='1234567'"
try:
    context.eval(code)                                                                                                      
except: 
	print(traceback.format_exc())  
`

So how do I know there is a global variable "random_name" ?

**Comment by PetterS** [comment]
`context.eval("globalThis.random_name !== undefined")`

**Comment by pianoboysai** [comment]
cool,  thank you very much,  if test_quickjs,py has this code, it will help.
