### ISSUE TITLE
How to reuse contexts

### ISSUE THREAD

**Issue by cemremengu** [PetterS/quickjs#37]
As context creation is expensive, is there a way to cleanup the internal state (variables) and reuse contexts?

**Comment by PetterS** [comment]
The complete life cycle of a runtime instance completes in less than 300 microseconds. What is your use case?

**Comment by cemremengu** [comment]
We are executing JS code based on incoming events from a stream (thousands per second).

On the same system, this takes *8 seconds*:

```python
import quickjs
import time

context = quickjs.Context()
context.add_callable("f", lambda x: x + 2)

start = time.time()
for x in range(1000000):
    context.eval("f(40)")
end = time.time()
print(end - start)
```

while this takes *300 seconds*

```python
start = time.time()
for x in range(1000000):
    context = quickjs.Context()
    context.add_callable("f", lambda x: x + 2)
    context.eval("f(40)")
end = time.time()
print(end - start)
```

Maybe my benchmark is wrong? Any suggestions?

**Comment by PetterS** [comment]
I see. No, there is no way to "clear" a context. 

You can wrap all your context in a JS class and create a new class whenever you need it.

**Comment by cemremengu** [comment]
Thanks for the quick reply and suggestion! I will continue to evaluate maybe its actually not so bad since it executes 1M callbacks in 5mins.
