### ISSUE TITLE
Is it possible to send list from python to quickjs?

### ISSUE THREAD

**Issue by cemremengu** [PetterS/quickjs#38]
Currently I am getting `Unsupported type when converting a Python object to quickjs: list.`

Is there a way? If not I can submit a PR with some pointers on how to implement this.

**Comment by PetterS** [comment]
Yes it is possible like this:
```
>>> from quickjs import Function                                                                                                                                                           >>> f = Function("f", "function f(a) { return a[1]; }")                                                                                                                                    >>> f([1, 2, 3])                                                                                                                                                                           2                                                                                                                                                                                          >>> 
```

**Comment by cemremengu** [comment]
My example is like this which doesnt work:

```python
import quickjs


def test_list():
    return [1, 2, 3]


def eval(script):
    context = quickjs.Context()
    context.add_callable("test_list", test_list)
    context.eval(script)


eval("test_list()")
```

```
TypeError: Unsupported type when converting a Python object to quickjs: list.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "js.py", line 14, in <module>
    eval("test_list()")
  File "js.py", line 11, in eval
    context.eval(script)
SystemError: <method 'eval' of '_quickjs.Context' objects> returned a result with an error set
```

**Comment by PetterS** [comment]
It is because you are using a `Context` and not a `Function`.

**Comment by PetterS** [comment]
But your example shows a bug in the error reporting. We should not raise a `SystemError` here. I will fix this.

**Comment by cemremengu** [comment]
Apologies if I am not making sense and thank you for your help. What I am looking for is that my `callable` returns a value back into the script, which I couldn't get to work with `Function` as well:

```
from quickjs import Function


def test_list():
    return []


def eval(script):
    f = Function("f", script)
    f.add_callable("test_list", test_list)
    f()


eval("function f(){ test_list() }")
```

**Comment by PetterS** [comment]
Indeed, sorry. You can do it like this:
```
import json
import quickjs


def test_list():
    return [1, 2, 3]

def test_list_wrapper():
    return json.dumps(test_list())

def eval(script):
    context = quickjs.Context()
    context.add_callable("test_list_wrapper", test_list_wrapper)
    context.eval("function test_list() { return JSON.parse(test_list_wrapper()); }")
    context.eval(script)


eval("test_list()")
```

**Comment by cemremengu** [comment]
Sorry my fault, I communicated the problem in a wrong way. Thanks so much.

Is there any chance to make (de)serialization process transparent to the user? I am willing to work on a PR with some guidance.

**Comment by PetterS** [comment]
I am reluctant to make the C code more complicated. Basic types are enough I think for that reason.

Lists are very complicated in dynamic languages like Python. For example:
```
def test_list():
    a = [1]
    a.append(a)
    return a
```

```
def test_list():
    a = [1]
    return [a, a]
```

These are quite difficult to convert to JS properly.

**Comment by simonlindholm3** [comment]
I think for symmetry with Function._call it would make sense to automatically JSON serialize objects/arrays. It's true that doing that on the C side is pretty complicated, however. Could be worth improving the error message to explain the situation, perhaps.

**Comment by SeaHOH** [comment]
Maybe we can put the results of the original value stored in the property, so without conversion when return to Python.

**Comment by cemremengu** [comment]
> I think for symmetry with Function._call it would make sense to automatically JSON serialize objects/arrays. It's true that doing that on the C side is pretty complicated, however. Could be worth improving the error message to explain the situation, perhaps.

Yes, I think it can *attempt* to do serialization and if the situation is too complex and fails, this can be communicated to user.

**Comment by cemremengu** [comment]
Another idea is that there can be a hook for serialization/conversion so users implement it however they want.

**Comment by qwenger** [comment]
> I think for symmetry with Function._call it would make sense to automatically JSON serialize objects/arrays. It's true that doing that on the C side is pretty complicated, however.

Just a quick thought on this: Python's C API allows importing and using modules, so the function `convert_args` in `_call` could be implemented 1:1 in `module.c`.

**Comment by PetterS** [comment]
I would like to keep the C code as small as possible though. To avoid things like this: https://github.com/PetterS/quickjs/pull/49
