### ISSUE TITLE
Add/set variables

### ISSUE THREAD

**Issue by qwenger** [PetterS/quickjs#54]
Hi,

quickjs provides ways of evaluating code and getting the result (`ctx.eval`), adding functions (`ctx.add_callable`) and getting values (`ctx.get`).

AFAICS, there is currently no proper way of adding/setting variables.

I've been able to work around this via json dumping:

```
ctx.eval(f"my_variable_name = {json.dumps(variable)};")
```

It however feels a bit hacky. I think that it would be nice to be able to set variables directly, e.g. as

```
ctx.set("my_variable_name", variable)
```

or by adding an optional argument to `eval`, which would bind the return value (js-side) of the evaluation to a variable:

```
ctx.eval(variable, "my_variable_name")
```

**Comment by PetterS** [comment]
A `set` method on a context sounds reasonable.

**Comment by qwenger** [comment]
Done in #55.
