### ISSUE TITLE
pip install for 1.16.0?

### ISSUE THREAD

**Issue by iansparks** [PetterS/quickjs#57]
Thanks for this library!

Latest on pypi is 1.15.1 but this lacks context.set() and I see 1.16.0 is available here but not published to pypi. 

Also quickjs  has a new release on 2021-03-27 : https://bellard.org/quickjs/Changelog

**Comment by PetterS** [comment]
Yes, it is time to update QuickJS and release a new version.

**Comment by iansparks** [comment]
Thanks! Any chance that Pypi will also be updated? https://pypi.org/project/quickjs/#history

**Comment by PetterS** [comment]
Yes, but I have a special computer that I use to build the Windows binaries. It is remarkably tricky.

**Comment by iansparks** [comment]
Yes, I understand! Thank you.
