### ISSUE TITLE
Memory leaks with callables

### ISSUE THREAD

**Issue by qwenger** [PetterS/quickjs#77]
The tests `test_can_eval_in_same_context` and `test_can_call_in_same_context` leak memory according to `check_memory.py`.

MWE:

```python
import _quickjs
context = _quickjs.Context()
context.add_callable("p", context.get("parseInt"))
```

In this example, `context_dealloc` won't ever be called, as can be shown using `gdb` and setting a breakpoint on it (the breakpoint won't trigger). Executing `context.gc()` or `del context` or `gc.collect()` do not help. Nor does deleting `p` in JS with a `context.eval`.

The reason may revolve around wrapped JS objects that retain a reference to the context, though I don't see a clear culprit yet.

**Comment by PetterS** [comment]
Thanks for pointing this out. We should fix this.

**Comment by 821938089** [comment]
add_callable bind an instance method can also cause memory leaks

example script
```python
import quickjs


class JsRuntime:
    def __init__(self):
        self.context = quickjs.Context()
        self.context.add_callable('some_func', self.some_func)

    def some_func(self):
        pass


def main():

    for _ in range(10000):
        JsRuntime()

    input('ok')


if __name__ == '__main__':
    main()
```
run the script and open task manager
![image](https://user-images.githubusercontent.com/8674809/156974603-296e4874-80f9-48ad-ac71-658e5267a463.png)

**Comment by qwenger** [comment]
@821938089 Could you please check your code with the PR #78 ? It may fix your issue as well.

**Comment by qwenger** [comment]
Nice! Then we need to wait for @PetterS to take action on #78 .
